import os
import tempfile
from unittest.mock import patch

import pytest


def test_warnings_import_missing_scenario():
    """Test to demonstrate what would happen if warnings import was missing."""

    # Create a mock generated file without warnings import
    mock_content = '''# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: test.proto
# plugin: python-betterproto

from dataclasses import dataclass
import betterproto


@dataclass(eq=False, repr=False)
class Foo(betterproto.Message):
    """ """
    
    old_field: str = betterproto.string_field(1)
    
    def __post_init__(self) -> None:
        warnings.warn("Foo is deprecated", DeprecationWarning)  # This would fail!
        super().__post_init__()
'''

    # Create a temporary file with the mock content
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
        f.write(mock_content)
        temp_file = f.name

    try:
        # Try to import the file - this should fail with NameError
        # We need to temporarily remove warnings from sys.modules to simulate the issue
        import sys

        original_warnings = sys.modules.get("warnings")

        # Temporarily remove warnings from sys.modules
        if "warnings" in sys.modules:
            del sys.modules["warnings"]

        try:
            with pytest.raises(NameError, match="name 'warnings' is not defined"):
                import importlib.util

                spec = importlib.util.spec_from_file_location("test_module", temp_file)
                if spec and spec.loader:
                    module = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(module)
        finally:
            # Restore warnings module
            if original_warnings:
                sys.modules["warnings"] = original_warnings
    finally:
        # Clean up
        os.unlink(temp_file)


def test_current_implementation_works():
    """Test that the current implementation correctly includes warnings import."""

    # Import the actual generated module
    from tests.output_betterproto.deprecated_message_option import Foo

    # This should work without NameError
    with pytest.warns(DeprecationWarning, match="Foo is deprecated"):
        foo = Foo(old_field="test")


def test_python_module_imports_logic():
    """Test the logic in python_module_imports method."""

    # This test verifies that the current implementation correctly includes warnings
    # when a message has the deprecated option set

    # Check the actual generated file content
    with open(
        "tests/output_betterproto/deprecated_message_option/__init__.py", "r"
    ) as f:
        content = f.read()

    # Verify warnings import is present
    assert "import warnings" in content, (
        "warnings import should be present in generated code"
    )

    # Verify warnings.warn calls are present
    assert "warnings.warn" in content, (
        "warnings.warn calls should be present in generated code"
    )

    # Verify DeprecationWarning is used
    assert "DeprecationWarning" in content, (
        "DeprecationWarning should be used in generated code"
    )


if __name__ == "__main__":
    # Run the tests
    pytest.main([__file__, "-v"])
